# Generated by Django 4.0.4 on 2022-06-29 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_userinfo_phone_number_userinfo_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': 'user info', 'verbose_name_plural': 'users info'},
        ),
    ]
