# Generated by Django 4.0.4 on 2022-07-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_data', '0002_alter_passengerinfo_airtraveleraccompaniedbyinfantind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengerinfo',
            name='airTravelerAccompaniedByInfantInd',
            field=models.CharField(max_length=250),
        ),
    ]
