# Generated by Django 4.0.4 on 2022-07-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_data', '0003_alter_passengerinfo_airtraveleraccompaniedbyinfantind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passengerinfo',
            name='airTravelerAccompaniedByInfantInd',
        ),
        migrations.AddField(
            model_name='passengerinfo',
            name='airTravelerABIInd',
            field=models.CharField(default='false', max_length=10),
            preserve_default=False,
        ),
    ]
