# Generated by Django 4.0.4 on 2022-07-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_data', '0004_remove_passengerinfo_airtraveleraccompaniedbyinfantind_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengerinfo',
            name='personNameNamePrefix',
            field=models.CharField(max_length=10),
        ),
    ]
