# Generated by Django 4.0.4 on 2022-07-31 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_data', '0005_alter_passengerinfo_personnamenameprefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedticket',
            name='stopQuantity',
            field=models.CharField(blank=True, default='0', max_length=5, null=True),
        ),
    ]
