# Generated by Django 4.0.4 on 2022-08-06 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_data', '0006_bookedticket_stopquantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedticket',
            name='echoToken',
            field=models.CharField(default=10001, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookedticket',
            name='fareRuleText',
            field=models.TextField(blank=True, null=True),
        ),
    ]
