# Generated by Django 4.0.4 on 2022-08-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_data', '0007_bookedticket_echotoken_bookedticket_fareruletext'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedticket',
            name='ticketStatus',
            field=models.CharField(choices=[('Booked', 'Booked'), ('Canceled', 'Canceled')], default='Booked', max_length=50),
            preserve_default=False,
        ),
    ]
