# Generated by Django 4.0.4 on 2022-09-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_data', '0008_bookedticket_ticketstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedticket',
            name='fareRuleText',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
