# Generated by Django 4.0.4 on 2022-09-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_data', '0009_alter_bookedticket_fareruletext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedticket',
            name='arrivalAirportLocationName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bookedticket',
            name='departureAirportLocationName',
            field=models.CharField(max_length=255),
        ),
    ]
