# Generated by Django 4.0.4 on 2022-09-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_data', '0010_alter_bookedticket_arrivalairportlocationname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedticket',
            name='arrivalAirportLocationCode',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bookedticket',
            name='companyCode',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bookedticket',
            name='departureAirportLocationCode',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bookedticket',
            name='equipmentAirEquipType',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bookedticket',
            name='return_ArrivalAirportLocationCode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bookedticket',
            name='return_DepartureAirportLocationCode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bookedticket',
            name='return_EquipmentAirEquipType',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bookedticket',
            name='return_OperatingAirlineCode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bookedticket',
            name='return_RPH',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bookedticket',
            name='return_StopQuantity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bookedticket',
            name='stopQuantity',
            field=models.CharField(blank=True, default='0', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bookedticket',
            name='totalFareCurrencyCode',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bookedticket',
            name='totalFareDecimalPlaces',
            field=models.CharField(max_length=50),
        ),
    ]
